In [3]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import random

In [13]:
set1 = [1, 2, 3]
lab_set = [0, 1]

n_exmp = 20

var1 = np.asarray([random.choice(set1) for ix in range(n_exmp)])
var2 = np.asarray([random.choice(set1) for ix in range(n_exmp)])
lab = np.asarray([random.choice(lab_set) for ix in range(n_exmp)])

print var1
print var2
print lab

[1 3 3 2 1 2 2 2 3 3 2 2 2 1 3 2 2 3 2 2]
[2 1 3 1 2 3 3 1 1 1 1 3 2 1 2 2 1 2 2 1]
[1 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0]


In [20]:
def probability(val, n_sample):
    cnt = 0
    
    for ix in range(n_sample.shape[0]):
        if n_sample[ix] == val:
            cnt += 1
    return float(cnt)/float(n_sample.shape[0])

def conditional_probability(c1, data, c2):
    n = lab.shape[0]
    count_c2 = 0
    count_c1_c2 = 0
    for ix in range(n):
        if lab[ix] == c2:
            count_c2 += 1
            if lab[ix] == c2 and data[ix] == c1:
                count_c1_c2 += 1
    return float(count_c1_c2)/float(count_c2)
            

print probability(1, var2)

0.45


In [32]:
def classify(inp):
    # for given input
    # decide probability for class 0
    
    prod_cond_prob = 1
    prod_pos_prob = 1
    
    prod_cond_prob *= conditional_probability(inp[0], var1, 0)
    prod_cond_prob *= conditional_probability(inp[1], var2, 0)
    
    prod_pos_prob *= probability(inp[0], var1)
    prod_pos_prob *= probability(inp[1], var2)
    
    p0 = probability(0, lab) * prod_cond_prob / prod_pos_prob
    
    prod_cond_prob = 1
    prod_pos_prob = 1
    
    prod_cond_prob *= conditional_probability(inp[0], var1, 1)
    prod_cond_prob *= conditional_probability(inp[1], var2, 1)
    
    print conditional_probability(inp[0], var1, 1)
    print conditional_probability(inp[1], var2, 1)
    
    prod_pos_prob *= probability(inp[0], var1)
    prod_pos_prob *= probability(inp[1], var2)
    
    print probability(inp[0], var1)
    print probability(inp[1], var2)

    
    p1 = (probability(1, lab) * prod_cond_prob) / prod_pos_prob
    
    return p0, p1

In [34]:
print var1
print var2
print lab

classify([2, 3])

[1 3 3 2 1 2 2 2 3 3 2 2 2 1 3 2 2 3 2 2]
[2 1 3 1 2 3 3 1 1 1 1 3 2 1 2 2 1 2 2 1]
[1 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0]
0.7
0.4
0.55
0.2


(0.0, 1.2727272727272725)

In [38]:
import sklearn
import pandas as pd
from sklearn.naive_bayes import GaussianNB

In [43]:
ds = pd.read_csv('./train.csv')
data_X = ds.values[:10000, 1:]
data_y = ds.values[:10000, 0]

test_X = ds.values[10000:15000, 1:]
test_y = ds.values[10000:15000, 0]

print data_X.shape, test_X.shape
print data_y.shape, test_y.shape

(10000, 784) (5000, 784)
(10000,) (5000,)


In [45]:
gnb = GaussianNB()

gnb.fit(data_X, data_y)

gnb.score(test_X, test_y)

0.55820000000000003

In [63]:
from sklearn.decomposition import PCA

pca = PCA(n_components=319)

dt = pca.fit_transform(ds.values[:15000, 1:])


In [64]:
trans_X = dt[:10000, :]
test_trans_X = dt[10000:, :]

print trans_X.shape

(10000, 319)


In [65]:
gnb = GaussianNB()

gnb.fit(trans_X, data_y)

gnb.score(test_trans_X, test_y)

0.79400000000000004